### ISSUE TITLE
RSS for news

### ISSUE THREAD

**Issue by rshadow** [lxc/linuxcontainers.org#212]
Please add RSS or Atom for news.

**Comment by stgraber** [comment]
Patches are welcome. Adding this would need some significant rework of the static website generator, to first know what a "news" is and then generate the relevant feeds.

**Comment by rshadow** [comment]
News on `https://linuxcontainers.org/[lxc|lxd|lxcfs|cgmanager]/news/` pages =)

**Comment by stgraber** [comment]
Sure, but the generator script has no idea what a news entry is so can't generate a feed unless it first gets the concept of a news entry.

**Comment by BobVul** [comment]
There's a feed available for the News category of the forum: https://discuss.linuxcontainers.org/c/news.rss

Unfortunately, there doesn't seem to be a way to get release notes only, so there's a bit of noise from the weekly status updates. Unless @stgraber can add an extra tag for releases?

**Comment by stgraber** [comment]
@BobVul done
https://discuss.linuxcontainers.org/tags/release

**Comment by BobVul** [comment]
Thanks!

So that means a release feed is available at https://discuss.linuxcontainers.org/tags/release.rss

It's also possible to browse tag intersections, e.g. LXD releases: https://discuss.linuxcontainers.org/tags/intersection/release/lxd

Unfortunately, it doesn't seem to be possible to get a feed of the tag intersection, but [that's a Discourse issue](https://meta.discourse.org/t/filter-by-multiple-tags-rss/74744).

**Comment by rshadow** [comment]
I am absolutely satisfied. Thank you.

Close the issue?

**Comment by stgraber** [comment]
Sounds good.
