### ISSUE TITLE
Try it backend documentation

### ISSUE THREAD

**Issue by techtonik** [lxc/linuxcontainers.org#289]
I want to extend whitelist for outgoing requests, so that testing anything with Fedora becomes possible, but can't find where try it backend is located. Worth mentioning in `README.md`.

**Comment by stgraber** [comment]
This is not part of any publicly accessible backend code for security reason.
Short of an agreement with whoever runs the Fedora infrastructure, try-it will not provide access to it.

The reason is that anything that try-it allows access to will be a potential target for attackers using the service and I simply don't have the time to deal with the potential legal issues that this involves.

That's why right now try-it only allows access to hosts that I personally control or that Canonical controls (and their sysadmin know what try-it is and how to react should there be some odd traffic patterns coming from it).

**Comment by techtonik** [comment]
I am not sure what attacks in particular are possible. If sandbox can not be protected then nobody can.

**Comment by stgraber** [comment]
Network attacks against the network targets, can be attempts at breaking other websites running on those servers, DoS of the package servers, ...

**Comment by techtonik** [comment]
So, that attack will be from LXD demo server. Is it that hard to trace it?

**Comment by stgraber** [comment]
The server records the container name and IP address that requested it, as well as what terms of service the user agreed to.

This is however not sufficient to track down who did what. The service being attacked will at best know what IP address the attack came from and when. Unfortunately the IP in question will be the one of the try-it server, not of a particular container (unless you have enough public IPs to give one per container).

Since we have an average of 10 concurrent sessions on our server, the timestamp and IP would only let us narrow it down to 10 potential IPs on our side, which means we'd fail to identify who actually attacked the remote service and so would be liable ourselves.

You could run a local proxy that intercepts both http and https traffic but that gets annoying to setup (requires TLS interception) but with that in place you could then log every request made out of every container and keep that log for whatever amount of time you may be held legally liable for depending on local jurisdiction.

Note that all of this may also depend on terms of service of your particular hosting provider. Whois records for most servers point to the provider, not to the operator and so the provider may decide to jump the gun and terminate your contract because of reported abuse even if you have proof that it's someone else.

**Comment by techtonik** [comment]
Even providers do not care that `IP != user`. =(
