### ISSUE TITLE
Changes for "Getting Started cli"

### ISSUE THREAD

**Issue by toby63** [lxc/linuxcontainers.org#412]
**Context:** 
https://linuxcontainers.org/lxd/getting-started-cli/
https://discuss.linuxcontainers.org/t/proposed-additions-and-changes-for-getting-started/7804
https://discuss.linuxcontainers.org/t/request-add-more-info-about-images-into-getting-started/7738

Todo:
Technical:
- [x] TOC (Table of Content)
- [x] Admonitions
- [x] Footnotes
- [x] Attribution Lists (use specific html classes)
- [x] FencedCode
- [ ] [blocked] other style for tables (reduced width, vertical borders) (also see: #420)

Content:
- [x] Initial Configuration
- [x] VM's [1]
- [x] Launch Instances [1]
- [x] Images [1]
- [x] Links [1]

Moved `Profiles` and `Tips&Tricks` to the Advanced Guide (#413).

[1]: see pull request #433

---

_Note: This is of course not urgent, but because I haven't received an answer in the forum, I wanted to post it here, so it would not be forgotten :slightly_smiling_face: ._

I would like to change some things in the "getting started-doc", but before I start to write a pull request for it, I would appreciate to get some answers (so I (and maybe others) know what you want to see included and what not):

1. Regarding general questions for editing (what is allowed etc.):
* can I add links to external websites, like:
    * official external documentation, e.g. [cloud-init](https://cloudinit.readthedocs.io/en/latest/topics/examples.html)?
    * blogs like simos blog: https://blog.simos.info/tag/lxd/ (only at the bottom, for "useful links" (or similar)) ?
* I guess everything should be as short as possible?

2. Regarding my ideas for changes;
I would add more info about:
* the options of `lxd-init` (like answers to "what is clustering?")
* VMs:
  should I seperate the vm-part from the container-part or mingle it (most topics like images, profiles etc. apply to both)?
  
* details for "lxc launch" (like requested in [this issue](https://github.com/lxc/linuxcontainers.org/issues/200))

* profiles (only short info + links)
    - extended info could be in the docs (https://linuxcontainers.org/lxd/docs/master/profiles), but would need a rewrite

* (maybe later) cloud-init (only short info + links):
     - extended info could be in the docs (["cloud-init"](https://linuxcontainers.org/lxd/docs/master/cloud-init), but would need a rewrite
     - potencial link: https://cloudinit.readthedocs.io/en/latest/topics/examples.html

* images:
  - "official" images (how to list, find and use them)
  - "download the images yourself"
       - maybe only a link to seperate documentation (would need a new page, maybe "images")
       - otherwise [link to imageserver](https://images.linuxcontainers.org/images/) and how to download & import the images
  - "building your own images":
      - maybe only a link to seperate documentation ("images"), otherwise:
           - link to [distrobuilder instructions](https://github.com/lxc/distrobuilder#creating-a-container-image)
          - link to [image templates](https://github.com/lxc/lxc-ci/tree/master/images)
          - extended info: e.g. about how to modify the image templates
  - link to [image handling](https://linuxcontainers.org/lxd/docs/master/image-handling) or include it in new document ("images")
      
* storage (pools) (only short info + links)
      
2.a) I would also like to add:
* a section for tips & tricks (for better workflow)
*  (useful) links:
   - To the [documentation](https://linuxcontainers.org/lxd/docs/master/index) and also:
      - [Security](https://linuxcontainers.org/lxd/docs/master/security) 
      - [FAQ](https://linuxcontainers.org/lxd/docs/master/faq)
      
   - To the forum: https://discuss.linuxcontainers.org/
                 

3. Regarding the layout of the document (what kind of layout/style do you prefer?); 
I would like to:
* add a Content-List at the beginning (so one can easier find content inside);
I created an example here: https://github.com/toby63/linuxcontainers.org/blob/master/content/lxd/getting-started-cli.md#content

* use tables to summarize flags, commands etc., I also created one example in the section about snap packages:
https://github.com/toby63/linuxcontainers.org/blob/master/content/lxd/getting-started-cli.md#snap-package-arch-linux-debian-fedora-opensuse-and-ubuntu

**Comment by stgraber** [comment]
1) Yeah, external links are fine. For the tutorials, we may want to link to the tutorial section on the forum instead where @simos is posting links to the tutorials and other content. Eventually I'd like to have all the posts there automatically linked directly from the website, but that will take a bunch of python code which I don't have time to write right now.

2) For consistency with help and doc, you should use `instances` for anything that applies to both containers and VMs and just highlight some of the little differences when it matters, that should avoid a lot of duplication.


All sounds good. For tables, I'm not sure whether the markdown setup we have in the website generator knows how to handle those. It may be an easy change to make them work though.


In any case, it's great that you want to work on this stuff. Our website does need quite a bit of updating but we've been struggling to get some time to do it... I'd recommend setting up a working environment on your machine where you can generate and access the updated website, then send many smaller PRs rather than one large one.

It's easier for us to review and also means changes go live faster. It also lets @tenforward and others translate things as they change rather than get one massive change that may take a while to translate.

**Comment by toby63** [comment]
Will close this now that #433 is merged.
Everything else will be included in the Advanced Guide.
