### ISSUE TITLE
Navigation above content in docs

### ISSUE THREAD

**Issue by nottrobin** [lxc/linuxcontainers.org#460]
On e.g. https://linuxcontainers.org/lxd/getting-started-cli/, I'm seeing the navigation first and then having to scroll down the see the content. I assume the navigation is intended to be to the left of the content, so you can start reading the content right away.

(I'm using Firefox 82 on Ubuntu 20.04)

![image](https://user-images.githubusercontent.com/519935/98929627-56545980-24d3-11eb-91a4-015dc702c720.png)

**Comment by stgraber** [comment]
Nope, it's intended to be a table of content and so be at the top.
I wouldn't be opposed to having it be navigation on the side but this is likely to be a problem given how long the entries are.
Maybe a better solution would be to have it in a collapsible section?

@toby63

**Comment by toby63** [comment]
Thank you for pinging me :slightly_smiling_face:.

:thinking: 
In general I always click on a topic in the navigation and this will get me right into the text, so I would not see a change as necessary, but I am open to changes if you want it.

I would advise against a **side navigation**, because imo the "long" and indented navigation is very useful for people who directly want to jump to a specific topic/section.

But a **collapsible section** could be a good compromise.
I would keep it open by default, so new users see it directly.
I assume that something like [this example of a collapsible section](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab#gistcomment-2818965) (that is open by default) could work with python-markdown, but I can also test it in a few days.

If it works, I would add it to the Advanced Guide as well.

**Comment by nottrobin** [comment]
Ah fair enough, if it's intended that's fine. I don't hate it.

If it's going to be expanded by default then I'm not sure making it collapsible is really necessary, as I would see the main drawback of the nav that you can't see the top of the document when you first visit the page.

If you think it's best in the layout it currently has, I'd suggest just leaving it as it is I think.

**Comment by toby63** [comment]
I tested the collapsible section method and in general it works, but it has two downsides:
1. The list needs to be in html (markdown inside the collapsible section does not work). I can easily convert the markdown lists, so I don't have to rewrite them, but still that is against the purpose of having mostly markdown source code.
2. For now I haven't found a method to place the title "Contents:" with bigger font size next to the arrow.
