### ISSUE TITLE
Startpage Suggestions

### ISSUE THREAD

**Issue by toby63** [lxc/linuxcontainers.org#516]
Related to: https://linuxcontainers.org/

1. I think `Infrastructure for Linux systems` is a bit confusing. Maybe there could be a better title.

2. "Deprecated projects: CGManager":
I think it should either be removed or changed in some ways, e.g. just a link to deprecated projects, so that it is more hidden.
Or at least some changes in the description, for example:
"CGManager ~~is~~ was our cgroup manager daemon"

3. `LXD`: mention that it uses LXC, to make the connection between the two clear and maybe advise users to use the easier method with LXD, instead of LXC.

4. `LXC`: 
   - `LXC is production ready with LTS releases coming with 5 years of security and bugfix updates.`: This is a bit confusing as well, while available LTS releases can be mentioned, I would also mention them for LXD. But `production ready` should be a basic assumption to every software that is not declared to be in alpha or beta status.
   - `LXC should not be confused with the lxc CLI client tool provided by LXD.`: While that is useful to know, especially new users will not know what this should be about. So I think this is not the right place for this information, it can mentioned somewhere else.
   - LXD could be mentioned here as well.

5. `LXCFS`: mention connection to LXD.

6. `Distrobuilder`: 
   - I would remove this part: `distrobuilder was created as a replacement for the old shell scripts that were shipped as part of LXC to generate images.`
   - mention the option to download ready-for-use images via LXD (created with distrobuilder)

**Comment by stgraber** [comment]
@ru-fu thoughts?

**Comment by ru-fu** [comment]
I opened https://github.com/lxc/linuxcontainers.org/pull/525 with some of the suggested changes.

> 1. I think `Infrastructure for Linux systems` is a bit confusing. Maybe there could be a better title.

I'm not a huge fan of the title, but I don't have a better suggestion. This came from the team, and it's better than just mentioning containers imo.

> 2. "Deprecated projects: CGManager":
>    I think it should either be removed or changed in some ways, e.g. just a link to deprecated projects, so that it is more hidden.

I shortened the description to give it a bit less focus (and moved that content to the CGManager introduction), but imo the distinction between active and deprecated is clear enough. When we end up having more deprecated projects, we should change the menu though to have a "Deprecated projects" link on the top instead of all deprecated projects directly.

> 3. `LXD`: mention that it uses LXC, to make the connection between the two clear and maybe advise users to use the easier method with LXD, instead of LXC.

In general for relating the different projects: I don't think we should do that on the start page. All the projects are part of linuxcontainers, so of course they are related, and the explanation on how they relate should be on the introduction pages (which will be reworked in the future).

>    * `LXC should not be confused with the lxc CLI client tool provided by LXD.`: While that is useful to know, especially new users will not know what this should be about. So I think this is not the right place for this information, it can mentioned somewhere else.

For me as a newbie, this was extremely confusing, and I've since seen it in other places that users assume that they are using "LXC commands" when running lxc. So I think it's important to have it, and in a prominent place.

>    * mention the option to download ready-for-use images via LXD (created with distrobuilder)

This is mentioned for LXD - why is it relevant for distrobuilder?

**Comment by tomponline** [comment]
>     1. Infrastructure for Linux systems

What about "Virtual infrastructure for Linux systems"?

**Comment by toby63** [comment]
> > ```
> > 1. Infrastructure for Linux systems
> > ```
> 
> What about "Virtual infrastructure for Linux systems"?

Sounds better.
But I still think thats a bit confusing.
Maybe it's because I am a foreigner but when I hear `infrastructure` I always think that someone wants to offer a service, like a server provider or cloud provider.
But here you offer a software, a tool to create containers and VMs.

So maybe something like:
- `Virtual environments for linux systems`
- `Virtualization for linux systems`
- `Software for virtualization of linux systems`

**Comment by stgraber** [comment]
I agree that "Infrastructure for Linux systems"doesn't really tell us a whole lot.
Worth noting that we likely need to stick under 35 chars to avoid wrapping (I hated how the old title was wrapped).

"Container and virtualization tools"? (exactly 35)

**Comment by ru-fu** [comment]
> "Container and virtualization tools"? (exactly 35)

If that doesn't give us problems with virtuali**z**ation/virtuali**s**ation?

**Comment by stgraber** [comment]
Don't think it'll be a problem :)

**Comment by ru-fu** [comment]
> Worth noting that we likely need to stick under 35 chars to avoid wrapping (I hated how the old title was wrapped).
It didn't fit (it's not only related to the number of characters, but also to the width of characters), but I decreased the font size a bit.

> I remember that I was confused the first time I got to know LXC and LXD; a short sentence mentioning that LXD is using LXC would make the situation much clearer and users would start with LXD instead of starting with LXC and noticing later that LXD is actually easier to use etc.
That's why we moved LXD on top now, since this is the most important tool and the one to start with.
I also added a short sentence to the LXC description now to make it clear that this is the basis, not the tool to use.

> Because people might assume that they have to build their images with distrobuilder.
I don't agree that this is an issue - we're very clear that LXD provides pre-built images.

**Comment by toby63** [comment]
Ok.

**Comment by toby63** [comment]
Closed with #525 and #527.
