### ISSUE TITLE
Create issue for release announcements

### ISSUE THREAD

**Issue by techtonik** [lxc/linuxcontainers.org#96]
Hi Stéphane,

Is it possible to crate issues or PRs for release announcements like ce975192c36? It is convenient to monitor progress on Linux containers through GiHub notification system, which only notifies about issues and PRs.

**Comment by Kentoseth** [comment]
@techtonik 

Do you want some type of system where github notifies you via the github interface that a new "Release" of LXD/LXC/etc. has been made?

I'm not sure this is the correct repo for it, as the issues we deal with in this repo relate to the LXC website.

**Comment by techtonik** [comment]
Yes. I want to see LXD releases in notifications.

**Comment by Kentoseth** [comment]
@techtonik 

I think the best option in that case is to 'watch' the LXD repo.

**Comment by stgraber** [comment]
We've since moved to publishing the announcements on the forum and have the website import from them. The forum has RSS and e-mail notifications that you can use.

We also update the tag on Github to include the release tarballs and link to the announcement on the forum, so the Github API would likely also work to look for new releases.
